#!/bin/bash -l
#SBATCH --job-name=hisat2-array
#SBATCH --array=1-56
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=4-05:005:00
#SBATCH --partition brc
#SBATCH --mem-per-cpu=6000MB
#SBATCH --mail-type=END,FAIL
# Autogenerated script from write_hisat2_script.R
# date Fri Feb  5 17:17:17 2021
# make sure directory paths exist before running script



module load apps/hisat2/2.1.0-python3.7.3



# Parse parameter file to get variables.
number=$SLURM_ARRAY_TASK_ID
paramfile=hisat2_param.txt
 
inr1=`sed -n ${number}p $paramfile | awk '{print $1}'`
inr2=`sed -n ${number}p $paramfile | awk '{print $2}'`
outsam=`sed -n ${number}p $paramfile | awk '{print $3}'`

# 9. Run the program.
hisat2 --trim5 10 --threads 4 -x /users/k1625253/scratch/old-scratch_rosalind-legacy-import_2020-01-28/Data/MetaData/GenomeIndex/hg38_spikein_hisat2/hg38/genome -1 $inr1 -2 $inr2 -S $outsam



